import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import { ThemeProvider } from "./theme"
import { Toaster } from "@/components/ui/toaster"
import { Navigation } from "@/components/common/nav"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Heimdallr Configurator",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <>
      <html lang="en" suppressHydrationWarning>
        <head>
          <script
            defer
            src="https://umami.ameow.xyz/script.js"
            data-website-id="3839aa7a-d2d0-465c-a0ec-7cdc0192f165"
          ></script>
        </head>
        <body>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
          <Toaster />
        </body>
      </html>
    </>
  )
}
